### ISSUE TITLE
glauth doesn't include plugins

### ISSUE THREAD

**Issue by aanderse** [sikmir/nur-packages#1]
Hi @sikmir :wave:

Thanks for packaging `glauth`! I think this software could very useful for me. I tried using the software and I don't believe the [plugins](https://github.com/glauth/glauth#make-commands) are being included in this package. Any chance you could include the plugins, or let me know if I am wrong?

**Comment by sikmir** [comment]
Yes, plugins were introduced in the latest glauth release 2.0.0. So I'll update this package to 2.0.0 and maybe it worth to open PR to nixpkgs.

**Comment by aanderse** [comment]
I would greatly appreciate that. Thank you so much!

**Comment by sikmir** [comment]
Now available in nixpkgs: https://github.com/NixOS/nixpkgs/issues/239396
